services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakeli-backend
    ports:
      - "80" # Fixed: Map host port 80 to container port 80
    env_file:
      - .env
    restart: unless-stopped
